// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATfhB9z-Vl-cGbfRX6yCB389EUbz9OcrI',
    appId: '1:836758077311:web:e87b68d6d9fd9dce7c244a',
    messagingSenderId: '836758077311',
    projectId: 'koko-authenticaion',
    authDomain: 'koko-authenticaion.firebaseapp.com',
    storageBucket: 'koko-authenticaion.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAOppLr3B3QO-Q-qplNgL9CI1aQXURPjM',
    appId: '1:836758077311:android:e27903d8502072627c244a',
    messagingSenderId: '836758077311',
    projectId: 'koko-authenticaion',
    storageBucket: 'koko-authenticaion.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyUf7yOzKtuE2CUupnUe_otCSTHXhHFeM',
    appId: '1:836758077311:ios:396096579e32b63b7c244a',
    messagingSenderId: '836758077311',
    projectId: 'koko-authenticaion',
    storageBucket: 'koko-authenticaion.firebasestorage.app',
    iosBundleId: 'com.example.kokoAuthentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyUf7yOzKtuE2CUupnUe_otCSTHXhHFeM',
    appId: '1:836758077311:ios:396096579e32b63b7c244a',
    messagingSenderId: '836758077311',
    projectId: 'koko-authenticaion',
    storageBucket: 'koko-authenticaion.firebasestorage.app',
    iosBundleId: 'com.example.kokoAuthentication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATfhB9z-Vl-cGbfRX6yCB389EUbz9OcrI',
    appId: '1:836758077311:web:865e83486f5c901a7c244a',
    messagingSenderId: '836758077311',
    projectId: 'koko-authenticaion',
    authDomain: 'koko-authenticaion.firebaseapp.com',
    storageBucket: 'koko-authenticaion.firebasestorage.app',
  );

}